table 'Actioned By Contact'
	lineageTag: 95740707-1076-48f7-b6d7-b7ccaf696a49

	column Contact_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5406e2bb-d6be-4dc9-892b-367f76a304cb
		summarizeBy: none
		sourceColumn: Contact_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ContactId
		dataType: string
		isHidden
		lineageTag: 3fddcaa3-a0e6-44cf-9aff-afb56e5c391a
		summarizeBy: none
		sourceColumn: ContactId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Contact Name'
		dataType: string
		lineageTag: faa54c5d-09d9-4b47-9ae5-afb4e3fe8bba
		summarizeBy: none
		sourceColumn: Contact Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: a459b8e0-2bd4-48d4-a69e-79158b9c5a76
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: b9cfbc68-2d06-4ce0-b142-4c3137f7a769
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b975eedb-47ff-4f5d-b529-761a161e5fb8
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition 'Actioned By Contact' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_Contact = Source{[Schema="mart",Item="Contact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(mart_Contact,{{"EmailAddress", "Email"}, {"CompanyName", "Company"}, {"Name", "Contact Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"_created", "_edited"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

