table Contact
	lineageTag: cc210300-f349-4b7d-94c4-5f5f87c1bbe6

	column Contact_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6419429b-b873-484e-890c-d41eb6eaaa33
		summarizeBy: none
		sourceColumn: Contact_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ContactId
		dataType: string
		isHidden
		lineageTag: 9ce95a9b-3255-472e-96ec-fecb685dfd40
		summarizeBy: none
		sourceColumn: ContactId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Contact Name'
		dataType: string
		lineageTag: 944bbf04-4bcb-4157-985e-dd4a7ba80771
		summarizeBy: none
		sourceColumn: Contact Name

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 284166f0-d04a-4a42-bac2-abef1a869fdd
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Contact = m
		mode: import
		source =
				let
				    Source = Sql.Database("CAKESOFBREAD", "WorkWalletBIClient_Local"),
				    mart_Contact = Source{[Schema="mart",Item="Contact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(mart_Contact,{{"Name", "Contact Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"_created", "_edited"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

