{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Induction\",\"Custom Question\",\"Custom Question Fact\",\"Induction Status\",\"Taken By\",\"Taken Status\",\"Wallet\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1126.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d9d09264-81b9-4632-bf43-4836b55cdccf",
        "fromColumn": "Created On",
        "fromTable": "Induction",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6cd50e72-c259-4411-9694-0da3a01f05bd"
      },
      {
        "name": "e7fe03a5-5028-43ed-a1e3-2e1f33504bd2",
        "fromColumn": "Taken On",
        "fromTable": "Taken By",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_705796de-106f-48c0-811d-f11b3483f209"
      },
      {
        "name": "0bc36e78-0610-41e2-8d96-5616c84e2c4a",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "InductionStatus_key",
        "fromTable": "Induction",
        "toColumn": "InductionStatus_key",
        "toTable": "Induction Status"
      },
      {
        "name": "a281c2d1-13fb-40dd-9bdd-abad6c1a2f09",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Wallet_key",
        "fromTable": "Induction",
        "toColumn": "Wallet_key",
        "toTable": "Wallet"
      },
      {
        "name": "ba5005a4-1c0c-4e45-ad1a-6bebc84b6288",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Wallet_key",
        "fromTable": "Custom Question",
        "isActive": false,
        "toColumn": "Wallet_key",
        "toTable": "Wallet"
      },
      {
        "name": "5eb7c9c1-5e28-4853-a905-0c36ce114d56",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "InductionCustomQuestion_key",
        "fromTable": "Custom Question Fact",
        "toColumn": "InductionCustomQuestion_key",
        "toTable": "Custom Question"
      },
      {
        "name": "0a377c76-55e7-4a7a-9cfd-624d76038b3c",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "InductionTaken_key",
        "fromTable": "Custom Question Fact",
        "toColumn": "InductionTaken_key",
        "toTable": "Taken By"
      },
      {
        "name": "f70a8fc3-8fb0-40af-8a63-82459392018b",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Wallet_key",
        "fromTable": "Custom Question Fact",
        "isActive": false,
        "toColumn": "Wallet_key",
        "toTable": "Wallet"
      },
      {
        "name": "403a341b-0092-4622-9367-5b2320d32cb3",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Induction_key",
        "fromTable": "Taken By",
        "toColumn": "Induction_key",
        "toTable": "Induction"
      },
      {
        "name": "912d7e2f-8b90-4be5-8ad7-d3d256dab310",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "InductionTakenStatus_key",
        "fromTable": "Taken By",
        "toColumn": "InductionTakenStatus_key",
        "toTable": "Taken Status"
      },
      {
        "name": "dda23af0-d9c4-4353-9466-028177a3fb80",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Wallet_key",
        "fromTable": "Taken By",
        "isActive": false,
        "toColumn": "Wallet_key",
        "toTable": "Wallet"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Induction",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Induction_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "55f2bdbb-32aa-4af4-9fed-acb365d95a1f",
            "sourceColumn": "Induction_key",
            "summarizeBy": "none"
          },
          {
            "name": "InductionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6ddb5c6b-138a-4c8e-9f32-3e1aa5c401b9",
            "sourceColumn": "InductionId",
            "summarizeBy": "none"
          },
          {
            "name": "Induction Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef013509-a1ae-4693-954a-8e5a4174dfca",
            "sourceColumn": "Induction Version",
            "summarizeBy": "none"
          },
          {
            "name": "Induction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "789f070e-1023-437a-9844-85028f2b7e36",
            "sourceColumn": "Induction",
            "summarizeBy": "none"
          },
          {
            "name": "Valid For Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27808086-e7d1-49cf-b40b-3b9bae2599f0",
            "sourceColumn": "Valid For Days",
            "summarizeBy": "none"
          },
          {
            "name": "Created On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9885d8b8-8212-460a-85a8-111b013854ac",
            "sourceColumn": "Created On",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6cd50e72-c259-4411-9694-0da3a01f05bd"
                },
                "isDefault": true,
                "relationship": "d9d09264-81b9-4632-bf43-4836b55cdccf"
              }
            ]
          },
          {
            "name": "Active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "86c7a1d1-00b6-4c13-9ae6-31586a9c266d",
            "sourceColumn": "Active",
            "summarizeBy": "none"
          },
          {
            "name": "InductionStatus_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4532bc4c-0473-4fc1-a0f4-04f974be7d88",
            "sourceColumn": "InductionStatus_key",
            "summarizeBy": "none"
          },
          {
            "name": "Test Pass Mark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c8b52f8-f0b5-4177-a4d2-7d961be096be",
            "sourceColumn": "Test Pass Mark",
            "summarizeBy": "sum"
          },
          {
            "name": "Test Question Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70cd8c03-e21b-4ce5-979c-f008b67632cd",
            "sourceColumn": "Test Question Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Wallet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9af9bc95-e850-4d23-9cf7-133b5588241d",
            "sourceColumn": "Wallet_key",
            "summarizeBy": "none"
          },
          {
            "name": "Induction Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0fa4357d-cd2a-41ec-a774-9304a4f5a059",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "6e1a15d5-e594-42b4-bf1b-14886a90b2b5",
        "partitions": [
          {
            "name": "Induction",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_Induction = Source{[Schema=\"mart\",Item=\"Induction\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_Induction,{\"_created\", \"_edited\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"InductionVersion\", \"Induction Version\"}, {\"InductionName\", \"Induction\"}, {\"ValidForDays\", \"Valid For Days\"}, {\"CreatedOn\", \"Created On\"}, {\"TestPassMark\", \"Test Pass Mark\"}, {\"TestQuestionCount\", \"Test Question Count\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_107499ea-2eac-40c2-b775-9a473148087d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "70ad59d5-34ca-4dd2-82a9-377d9f292735",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0b9390be-3519-42da-9d34-1bc9a0f2a978",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "43b7358c-bd3d-49f1-907a-cddaccba2502",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3121429b-be7d-4d27-8047-3ff37676b8c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c52e2a20-ec0d-4ae1-b53c-284e9f9335fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "91d8c8a9-e696-4a25-b3d1-a014f7ed7089",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8e268ac4-cada-4aba-aa46-73a9aec319fa",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cbdb2e48-abf5-4a1a-9cf9-76578bcba8bd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "03e4e03a-8730-4a52-a0da-3069b9514f0c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "50f81771-18f3-41e3-ab96-cda8e071bac7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "76bbbf30-020d-4137-aaa5-070a4715f64f",
                "ordinal": 3
              }
            ],
            "lineageTag": "04e768de-e16d-460c-9a28-21a4b5a13930"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "7d7d573a-b709-4c73-b85c-098a94359bf8",
        "partitions": [
          {
            "name": "DateTableTemplate_107499ea-2eac-40c2-b775-9a473148087d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6cd50e72-c259-4411-9694-0da3a01f05bd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1f787363-7553-4221-aa8a-6d37f2a29479",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "364c4714-872d-4fb8-bc2e-877d76df5f90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5d28a1e9-8a1f-4a5a-9970-ba02e68f4377",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a131b9de-1f2b-469a-a8f0-6eb1ceba1b99",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "be8cdf6b-65ad-45e3-bb4e-f9422ffbb0c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1d848a3c-5a5d-450d-bd4f-0e55c18a8e54",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4208e261-0360-4eeb-96f0-546e3dc367b3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fd425e22-5f19-4855-993b-b63e655d5e4b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b749f3f1-76a9-40b4-860c-47f2e6da37f9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2173aef5-cd9a-45fc-9757-4467885bf61d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7aa04421-9b18-476b-a53a-f605bea6ad9d",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a11da61-c497-40e2-b3f9-7848f009c680"
          }
        ],
        "isHidden": true,
        "lineageTag": "54c1c302-30ff-401e-b12f-07b93caf606d",
        "partitions": [
          {
            "name": "LocalDateTable_6cd50e72-c259-4411-9694-0da3a01f05bd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Induction'[Created On])), 1, 1), Date(Year(MAX('Induction'[Created On])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Custom Question",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "InductionCustomQuestion_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a730dc79-508b-4f58-95b1-34287d1ef542",
            "sourceColumn": "InductionCustomQuestion_key",
            "summarizeBy": "none"
          },
          {
            "name": "Question",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c942ff4-0a4c-4b8d-82aa-f479e7dae920",
            "sourceColumn": "Question",
            "summarizeBy": "none"
          },
          {
            "name": "Answer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88a4c5b4-35d2-4d4a-96fb-47edaf401850",
            "sourceColumn": "Answer",
            "summarizeBy": "none"
          },
          {
            "name": "Wallet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7df8c6fe-418f-46da-a7ce-33da63375915",
            "sourceColumn": "Wallet_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2cde93b0-9f3a-47bd-ae2b-296e2fa527be",
        "partitions": [
          {
            "name": "Custom Question",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_InductionCustomQuestion = Source{[Schema=\"mart\",Item=\"InductionCustomQuestion\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_InductionCustomQuestion,{\"_created\", \"_edited\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Title\", \"Question\"}, {\"Value\", \"Answer\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Custom Question Fact",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "InductionTaken_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9234850d-367b-4534-ad5e-7b5529063532",
            "sourceColumn": "InductionTaken_key",
            "summarizeBy": "none"
          },
          {
            "name": "InductionCustomQuestion_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "707c6d55-08ca-4893-a8e8-9ace7362c21b",
            "sourceColumn": "InductionCustomQuestion_key",
            "summarizeBy": "none"
          },
          {
            "name": "Wallet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6790233-3a51-4618-ac27-760403650e0b",
            "sourceColumn": "Wallet_key",
            "summarizeBy": "none"
          },
          {
            "name": "Custom Question Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f9482763-9c8b-44c6-ad25-dcae56f4622e",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "6c16818b-37c8-4bb1-a2d1-ac0aa04be04c",
        "partitions": [
          {
            "name": "Custom Question Fact",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_InductionCustomQuestionFact = Source{[Schema=\"mart\",Item=\"InductionCustomQuestionFact\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_InductionCustomQuestionFact,{\"_created\", \"_edited\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Induction Status",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "InductionStatus_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9c3c4c0d-d7aa-4030-b1f5-98861af90489",
            "sourceColumn": "InductionStatus_key",
            "summarizeBy": "none"
          },
          {
            "name": "InductionStatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f1bb5208-eabb-4750-abd2-1e1f9b169407",
            "sourceColumn": "InductionStatusCode",
            "summarizeBy": "none"
          },
          {
            "name": "Induction Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de9972f3-8d36-442a-8498-10b848401109",
            "sourceColumn": "Induction Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f45f30e-0240-4cef-b7f1-b3acbfac9612",
        "partitions": [
          {
            "name": "Induction Status",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_InductionStatus = Source{[Schema=\"mart\",Item=\"InductionStatus\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_InductionStatus,{\"_created\", \"_edited\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"InductionStatus\", \"Induction Status\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Taken By",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "InductionTaken_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62e311e6-ea22-40b5-b792-4a3d6d90341f",
            "sourceColumn": "InductionTaken_key",
            "summarizeBy": "none"
          },
          {
            "name": "InductionTakenId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ce2ab0a6-953f-4f31-bb2d-e3f7bc53aa07",
            "sourceColumn": "InductionTakenId",
            "summarizeBy": "none"
          },
          {
            "name": "Induction_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cf9214c9-96c4-402a-8e71-e3e22f3d7652",
            "sourceColumn": "Induction_key",
            "summarizeBy": "none"
          },
          {
            "name": "ContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f5785f70-29d2-47d9-8cab-6cecd479f436",
            "sourceColumn": "ContactId",
            "summarizeBy": "none"
          },
          {
            "name": "Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae8ae6e3-2949-4657-836c-7387058de3ce",
            "sourceColumn": "Person",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6df6b81-341e-4cee-946b-5e8d2206b03f",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "Taken On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8ba6e657-d8cb-4831-b2ec-ac972b819fd5",
            "sourceColumn": "Taken On",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_705796de-106f-48c0-811d-f11b3483f209"
                },
                "isDefault": true,
                "relationship": "e7fe03a5-5028-43ed-a1e3-2e1f33504bd2"
              }
            ]
          },
          {
            "name": "Correct Test Question Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7da737c-fc35-425e-8f0c-ec023946b209",
            "sourceColumn": "Correct Test Question Count",
            "summarizeBy": "sum"
          },
          {
            "name": "InductionTakenStatus_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "702c6e8a-2714-4bba-b495-3f212b9dab5a",
            "sourceColumn": "InductionTakenStatus_key",
            "summarizeBy": "none"
          },
          {
            "name": "Wallet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "28c28133-6a2b-4db1-91e9-de12acc99736",
            "sourceColumn": "Wallet_key",
            "summarizeBy": "none"
          },
          {
            "name": "Taken By Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "391cf8aa-c679-486c-8be1-1d5c4b1123ac",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d1c39eb9-26d7-4578-8a92-f5277ee0bc30",
        "partitions": [
          {
            "name": "Taken By",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_InductionTaken = Source{[Schema=\"mart\",Item=\"InductionTaken\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_InductionTaken,{\"_created\", \"_edited\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"CompanyName\", \"Company\"}, {\"TakenOn\", \"Taken On\"}, {\"CorrectTestQuestionCount\", \"Correct Test Question Count\"}, {\"Name\", \"Person\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_705796de-106f-48c0-811d-f11b3483f209",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0a6605d9-9a78-442d-a7dc-06bb998041b8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0397f779-22b2-4ac8-950f-1d8716cc0875",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7f0b068d-6a4a-44cb-82e3-1dda1ea37870",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "740b5319-01ea-40d9-96e9-52dd46f9da43",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dfce10fb-c1ce-435c-8922-b1601f5f6afa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "34594771-55f1-472d-be74-380992b59ed9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "84994ff3-34ea-4e44-953b-9901093035ea",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a270afb8-8b6a-44b3-9656-4f140d1509fa",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "844758a7-b1c6-469f-9d32-5c23517ce776",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4c828b56-5375-4cbc-87ae-cb03ba1e7179",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c271f30b-32a6-4337-98da-136cef34b1a0",
                "ordinal": 3
              }
            ],
            "lineageTag": "3b9dc11a-b42a-4b49-ac33-7531d7f2e354"
          }
        ],
        "isHidden": true,
        "lineageTag": "5911ff80-3442-4363-bce2-03949010ecaa",
        "partitions": [
          {
            "name": "LocalDateTable_705796de-106f-48c0-811d-f11b3483f209",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Taken By'[Taken On])), 1, 1), Date(Year(MAX('Taken By'[Taken On])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Taken Status",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "InductionTakenStatus_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3c1d2b5c-d0d8-4dff-9857-8ed077faf427",
            "sourceColumn": "InductionTakenStatus_key",
            "summarizeBy": "none"
          },
          {
            "name": "InductionTakenStatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a0fcf6d-3289-4da4-8974-a357211ddf16",
            "sourceColumn": "InductionTakenStatusCode",
            "summarizeBy": "none"
          },
          {
            "name": "Taken Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c0830fb-4a15-42d9-bfb2-982b0f7bdbdd",
            "sourceColumn": "Taken Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2f658f03-ab11-43c9-af1e-06d19a216afd",
        "partitions": [
          {
            "name": "Taken Status",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_InductionTakenStatus = Source{[Schema=\"mart\",Item=\"InductionTakenStatus\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_InductionTakenStatus,{\"_created\", \"_edited\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"InductionTakenStatus\", \"Taken Status\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Wallet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Wallet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "752ef2a4-e4ec-4d06-b725-e9fc5cd505b4",
            "sourceColumn": "Wallet_key",
            "summarizeBy": "none"
          },
          {
            "name": "WalletId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0f3fe48e-ceda-442b-aacb-490b448ec5a3",
            "sourceColumn": "WalletId",
            "summarizeBy": "none"
          },
          {
            "name": "Wallet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65fdd2bd-6d97-44df-bd76-b7315129aa72",
            "sourceColumn": "Wallet",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6c2a96a-198a-4dd1-9452-989cd707929c",
        "partitions": [
          {
            "name": "Wallet",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"(LocalDB)\\MSSQLLocalDB\", \"WorkWalletBIClient\"),",
                "    mart_Wallet = Source{[Schema=\"mart\",Item=\"Wallet\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(mart_Wallet,{\"_created\", \"_edited\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}