table 'Checklist Answer'
	lineageTag: 8e3f3544-12c0-4977-9d51-2046ec21ca3d

	column PermitChecklistAnswer_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ab1bbcbd-a982-43b1-90da-8a85a37a46ab
		summarizeBy: none
		sourceColumn: PermitChecklistAnswer_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Section Type'
		dataType: string
		lineageTag: d9d5fc77-1da0-426f-a487-a0f483bbf3ca
		summarizeBy: none
		sourceColumn: Section Type

		annotation SummarizationSetBy = Automatic

	column Question
		dataType: string
		lineageTag: 7d5bec45-b89d-40fb-9a79-b4d5a7efb046
		summarizeBy: none
		sourceColumn: Question

		annotation SummarizationSetBy = Automatic

	column Answer
		dataType: string
		lineageTag: 6ac805ac-5059-4af3-a780-ba3767d34575
		summarizeBy: none
		sourceColumn: Answer

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1792ded7-0d42-4618-b304-18b0fa48e021
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Checklist Answer' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_PermitChecklistAnswer = Source{[Schema="mart",Item="PermitChecklistAnswer"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_PermitChecklistAnswer,{"_edited", "_created"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CategorySectionType", "Section Type"}, {"Option", "Answer"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

