table 'Checklist Answer Fact'
	lineageTag: 85685a26-4860-4aa5-af79-e396ebb40c0d

	column Permit_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8bdb6408-45e4-469b-8900-b17d865192aa
		summarizeBy: none
		sourceColumn: Permit_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column PermitChecklistOption_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 99bbb9d5-7a02-4a3f-bc8c-1c0fb768ff00
		summarizeBy: none
		sourceColumn: PermitChecklistOption_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 57f04a17-2d77-4245-9c76-922a51ffb1dd
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Checklist Answer Count' = 1
		formatString: 0
		lineageTag: 86f0d861-80fb-4336-9185-0ef7529b4d4e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Checklist Answer Fact' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_PermitChecklistAnswerFact2 = Source{[Schema="mart",Item="PermitChecklistAnswerFact2"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_PermitChecklistAnswerFact2,{"_created"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

