table Contact
	lineageTag: b1cc4af9-ba09-44fa-bfba-3c45a91b7a39

	column Contact_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e90b9d82-b482-45a1-a98d-50e10f52e95f
		summarizeBy: none
		sourceColumn: Contact_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContactId
		dataType: string
		isHidden
		lineageTag: 3e62fe4c-fa41-4f05-a050-aa8577f6f671
		summarizeBy: none
		sourceColumn: ContactId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Contact Name'
		dataType: string
		lineageTag: d87230f5-a268-4e94-8735-de86ddcecfae
		summarizeBy: none
		sourceColumn: Contact Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 0f2ee0f3-4471-4811-b67e-23a40edbbeb8
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 5631028c-5488-4ae3-8699-055ef4bc0816
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e4ac64fb-32b1-47f1-90e9-94598831825b
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition Contact = m
		mode: import
		source =
				let
				  Source = Sql.Database("demo-workwalletbi.database.windows.net", "demo-workwalletbi"),
				  #"Navigation 1" = Source{[Schema = "mart", Item = "Contact"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CompanyName", "Company"}, {"EmailAddress", "Email"}, {"Name", "Contact Name"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

