table Contact
	lineageTag: cc210300-f349-4b7d-94c4-5f5f87c1bbe6

	column Contact_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6419429b-b873-484e-890c-d41eb6eaaa33
		summarizeBy: none
		sourceColumn: Contact_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContactId
		dataType: string
		isHidden
		lineageTag: 9ce95a9b-3255-472e-96ec-fecb685dfd40
		summarizeBy: none
		sourceColumn: ContactId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Contact Name'
		dataType: string
		lineageTag: 944bbf04-4bcb-4157-985e-dd4a7ba80771
		summarizeBy: none
		sourceColumn: Contact Name

		annotation SummarizationSetBy = Automatic

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 284166f0-d04a-4a42-bac2-abef1a869fdd
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Email
		dataType: string
		lineageTag: a345e00e-6c58-4e9f-b0c6-4639ca6425f6
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 87574ed9-a961-45e5-82df-12c577fe4ec2
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition Contact = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_Contact = Source{[Schema="mart",Item="Contact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(mart_Contact,{{"Name", "Contact Name"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"_created", "_edited"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"EmailAddress", "Email"}, {"CompanyName", "Company"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

