table 'Numeric Question'
	lineageTag: 1046a9a6-0c1a-4aba-97d3-908952785237

	column AuditNumericQuestion_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 002ffd6b-a1d8-4126-91a7-2dffa9fa6faa
		summarizeBy: none
		sourceColumn: AuditNumericQuestion_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column QuestionId
		dataType: string
		isHidden
		lineageTag: 5bec49ad-587d-4ee3-808d-5204f05d6396
		summarizeBy: none
		sourceColumn: QuestionId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Numeric Question'
		dataType: string
		lineageTag: 732d2961-d2e0-4e75-b129-cd2cccc56b63
		summarizeBy: none
		sourceColumn: Numeric Question

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 02bab8e0-698b-4c6f-8f04-8da1ed29f294
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column Scale
		dataType: int64
		formatString: 0
		lineageTag: 96e9b0a8-ee6d-46c6-808d-90fa3ecc9a3c
		summarizeBy: none
		sourceColumn: Scale

		annotation SummarizationSetBy = User

	column Unit_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2fa1dd09-7213-44bc-af6c-141b093960a2
		summarizeBy: none
		sourceColumn: Unit_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 74692309-a8d3-4c25-b49e-3e9af60ec632
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Unit = RELATED(Unit[Unit])
		lineageTag: acbdd418-a5bb-4f4c-9503-f3d422dd5139
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Unit Acronym' = RELATED(Unit[Unit Acronym])
		lineageTag: 4d6e2eb3-bde3-45bb-84b4-1a2ddcef82da
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Numeric Question' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_AuditNumericQuestion = Source{[Schema="mart",Item="AuditNumericQuestion"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_AuditNumericQuestion,{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Question", "Numeric Question"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

