table Asset
	lineageTag: 1fbdd36a-5356-45f3-8c79-63344009ee01

	column Asset_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2135c0d1-7bcb-41a1-bae1-6628bea7573a
		summarizeBy: none
		sourceColumn: Asset_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AssetId
		dataType: string
		isHidden
		lineageTag: e1016ea4-192f-4e21-b570-974785bb14ab
		summarizeBy: none
		sourceColumn: AssetId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Asset Type'
		dataType: string
		lineageTag: da46f7ca-2971-4ea1-9208-82e7d3c4dacf
		summarizeBy: none
		sourceColumn: Asset Type

		annotation SummarizationSetBy = Automatic

	column AssetStatus_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2629575c-5876-424f-aab6-7490d4b041f6
		summarizeBy: none
		sourceColumn: AssetStatus_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Reference
		dataType: string
		lineageTag: e4ba0696-0b1a-4d0f-a203-8cba4433274b
		summarizeBy: none
		sourceColumn: Reference

		annotation SummarizationSetBy = Automatic

	column 'Asset Name'
		dataType: string
		lineageTag: d445a91f-a16a-4cd0-821d-492c931a4d0c
		summarizeBy: none
		sourceColumn: Asset Name

		annotation SummarizationSetBy = Automatic

	column 'Asset Notes'
		dataType: string
		lineageTag: 42071586-7246-443b-a024-3a27bc4e6828
		summarizeBy: none
		sourceColumn: Asset Notes

		annotation SummarizationSetBy = Automatic

	column 'Created On'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 353e3857-f920-4767-b857-81a04ffac03d
		summarizeBy: none
		sourceColumn: Created On

		variation Variation
			isDefault
			relationship: 10c11389-33ee-4a59-876a-424adf1193ea
			defaultHierarchy: LocalDateTable_37a1848f-35ef-46e0-8dbf-84012bdaf89c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4d312161-a638-4c02-8f22-2ac5f3dfe1de
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Asset Count' = 1
		formatString: 0
		lineageTag: 26b70d5a-fc07-4f3a-801b-f18269f49f16
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Asset = Asset[Asset Type] & " - " & Asset[Asset Name]
		lineageTag: ae9028e5-4a79-4ec9-b68f-a45fe27358c4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Open Defects' =
			
			COALESCE(
			    SUMX(
			        RELATEDTABLE(Observation),
			        Observation[Open Defect Count]
			    ),
			    0
			)
		formatString: 0
		lineageTag: fafaaf74-756a-46cd-86dc-f5ab75aaf303
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Latest Assigned To' =
			
			CALCULATE(
			    SELECTEDVALUE(Assignment[Assigned To]),
			    'Assignment Fact'[Is Latest] = TRUE
			)
		lineageTag: 8c62c53f-00d1-41b1-89c9-0c8c5f5a0543
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Inspection Date' =
			
			COALESCE(
			    MAXX(
			        RELATEDTABLE(Inspection),
			        Inspection[Inspection Date]
			    ),
			    BLANK()
			)
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 8b80a8f4-74dd-4037-a804-269f97bb91c7
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 72f3b611-7593-498f-8568-418cf232178e
			defaultHierarchy: LocalDateTable_63a987a6-743d-4041-aed1-6b8fe393d68e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Defective Count' = IF(Asset[Open Defects] > 0, 1, 0)
		dataType: int64
		formatString: 0
		lineageTag: f41da1cc-93ac-4d3d-b9d9-8b88441173dc
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Assigned Count' =
			
			IF(
			    CALCULATE(
			        COUNTROWS('Assignment Fact'),
			        'Assignment Fact'[Is Latest] = TRUE(),
			        'Assignment Type'[Assignment Type] <> "Unassigned"
			    ) > 0,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 5ccf45e8-58be-4bec-91ff-ed51903c6035
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Unassigned Count' = 1 - [Assigned Count]
		formatString: 0
		lineageTag: f53223c4-64fe-4136-8cc5-731be9425a7d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Asset = m
		mode: import
		source =
				let
				    Source = Sql.Database("CAKESOFBREAD", "WorkWalletBIClient_Local"),
				    mart_Asset = Source{[Schema="mart",Item="Asset"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_Asset,{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Name", "Asset Name"}, {"Description", "Asset Notes"}, {"CreatedOn", "Created On"}, {"AssetType", "Asset Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

