table Inspection
	lineageTag: 9cb6e7f8-8551-4efe-946a-8bf11e22d406

	column AssetInspection_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d9b90760-5b2f-455f-b329-c9e5ff7426d0
		summarizeBy: none
		sourceColumn: AssetInspection_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InspectionId
		dataType: string
		isHidden
		lineageTag: cd1cb9f1-ac2b-4862-9810-07083afc48cc
		summarizeBy: none
		sourceColumn: InspectionId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Asset_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 85221f72-b56b-4e0f-9c1e-f69e3594589a
		summarizeBy: none
		sourceColumn: Asset_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 850f3091-7731-4b0e-8210-281b6d261511
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Inspection Count' = 1
		formatString: 0
		lineageTag: e42efbe9-d186-4b6a-87f9-c460f957817a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Defects Raised' =
			
			VAR CurrentInspectionKey = Inspection[AssetInspection_key]
			RETURN
			COALESCE(
			    CALCULATE(
			        SUMX(
			            FILTER(
			                'Inspection Observation Fact',
			                'Inspection Observation Fact'[AssetInspection_key] = CurrentInspectionKey
			                    && 'Inspection Observation Fact'[New] = TRUE
			            ),
			            VAR ObsKey = 'Inspection Observation Fact'[AssetObservation_key]
			            RETURN
			            CALCULATE(
			                SUM(Observation[Defect Count]),
			                Observation[AssetObservation_key] = ObsKey
			            )
			        )
			    ),
			    0
			)
		formatString: 0
		lineageTag: f58918ea-08bc-4766-903a-12739c408073
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column AssetInspectionStatus_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d9c56e96-43de-45eb-80de-08bcc2e1ef65
		summarizeBy: none
		sourceColumn: AssetInspectionStatus_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column AssetInspectionType_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5bbd9e5b-261d-4f00-afdf-60eeffad206d
		summarizeBy: none
		sourceColumn: AssetInspectionType_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Inspected On'
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 4258a6af-d4e6-466c-ad18-bf936f0d6679
		summarizeBy: none
		sourceColumn: Inspected On

		variation Variation
			isDefault
			relationship: 19c68a27-c72c-4ee1-9131-9c2ce7c08865
			defaultHierarchy: LocalDateTable_6f97f8c7-3065-4a3a-a9af-6233a93072c8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Score
		dataType: int64
		formatString: 0
		lineageTag: e577f3ae-20f0-4c53-b30b-136e793a8373
		summarizeBy: sum
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column 'Potential Score'
		dataType: int64
		formatString: 0
		lineageTag: 551cc136-bc17-48bc-8841-ad44b8a038a7
		summarizeBy: sum
		sourceColumn: Potential Score

		annotation SummarizationSetBy = Automatic

	column 'Average Score'
		dataType: double
		lineageTag: e5f058bd-3af1-40c2-9161-e4da0162c582
		summarizeBy: none
		sourceColumn: Average Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Average Potential Score'
		dataType: double
		lineageTag: 2493031d-0a85-4b35-8402-1be88c07a893
		summarizeBy: none
		sourceColumn: Average Potential Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage Score'
		dataType: double
		lineageTag: 2c7b6f32-89fd-44e7-92bd-5f295dd9c99d
		summarizeBy: none
		sourceColumn: Percentage Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Defects
		dataType: int64
		formatString: 0
		lineageTag: 25aa4731-1bfc-424b-98b4-3bc1416b589c
		summarizeBy: sum
		sourceColumn: Defects

		annotation SummarizationSetBy = Automatic

	column Passed
		dataType: int64
		formatString: 0
		lineageTag: 0d6a8d8b-f993-4e5f-b5da-d24045ddf505
		summarizeBy: none
		sourceColumn: Passed

		annotation SummarizationSetBy = User

	column GradingSetOption_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bc9fa6b9-b29d-4c30-aff1-42735855daac
		summarizeBy: none
		sourceColumn: GradingSetOption_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'External Identifier'
		dataType: string
		lineageTag: 806f3c13-43fb-4ec8-8c6f-cc19210e0f18
		summarizeBy: none
		sourceColumn: External Identifier

		annotation SummarizationSetBy = Automatic

	column 'Inspected By Company'
		dataType: string
		lineageTag: 5cfcabbe-0951-4349-af8e-6e969c36ad3e
		summarizeBy: none
		sourceColumn: Inspected By Company

		annotation SummarizationSetBy = Automatic

	column 'In Progress Status Date'
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 016b44ba-8938-4788-8b6c-b874dde3fa1a
		summarizeBy: none
		sourceColumn: In Progress Status Date

		variation Variation
			isDefault
			relationship: afda8e88-ee83-4052-9a13-46b15790ecb4
			defaultHierarchy: LocalDateTable_667c89c4-6ac5-42c7-ae87-415e9f161b4a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ready For Review Status Date'
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 1d2e3187-cec8-49b2-a549-cc4ce8558f61
		summarizeBy: none
		sourceColumn: Ready For Review Status Date

		variation Variation
			isDefault
			relationship: 42f4b742-8adf-4b83-b4e9-e423a2f41f7d
			defaultHierarchy: LocalDateTable_724f1fd4-ed70-495c-9bec-2ae3a2ca53fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Complete Status Date'
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 5856d7ef-ae00-4e49-8cac-7dc103fb2839
		summarizeBy: none
		sourceColumn: Complete Status Date

		variation Variation
			isDefault
			relationship: ac4d0801-09ad-4139-9259-5efd37706b56
			defaultHierarchy: LocalDateTable_cbf297e1-76d7-4564-a3c8-52c69430838f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Archived Status Date'
		dataType: dateTime
		formatString: dd/mm/yyyy hh:nn
		lineageTag: 0a2b1a1a-a374-4401-97ea-e19f8112cdf3
		summarizeBy: none
		sourceColumn: Archived Status Date

		variation Variation
			isDefault
			relationship: 648dac71-2229-4a82-a6a7-9d17cb0a23b8
			defaultHierarchy: LocalDateTable_a50c46dd-af9d-44c6-ab1d-e8e6381159df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Score Display' =
			
			VAR DisplayScore =
			    AND(RELATED('Inspection Type'[Display Total Score]), Inspection[Score] <> -1)
			VAR DisplayPercentage =
			    AND(RELATED('Inspection Type'[Display Percentage]), Inspection[Percentage Score] <> -1)
			VAR ScoreText =
			    IF(DisplayScore, Inspection[Score] & "/" & Inspection[Potential Score], "")
			VAR PercentageText =
			    IF(DisplayPercentage, FORMAT(Inspection[Percentage Score], "#%"), "")
			RETURN
			    IF(
			        RELATED('Inspection Type'[Scoring Enabled]),
			        IF(
			            AND(DisplayScore, DisplayPercentage),
			            ScoreText & " (" & PercentageText & ")",
			            IF(
			                DisplayScore,
			                ScoreText,
			                IF(
			                    DisplayPercentage,
			                    PercentageText,
			                    ""
			                )
			            )
			        ),
			        "scoring not enabled"
			    )
		lineageTag: 3a7dfec0-38e6-4f62-8a34-5b3c0e83b454
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Inspected By' = CONCATENATEX (RELATEDTABLE(Contact), Contact[Contact Name], ", ", Contact[Contact Name], ASC)
		lineageTag: 648411c9-6a78-4366-b241-528532136a49
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Inspection = m
		mode: import
		source =
				let
				    Source = Sql.Database("demo-workwalletbi.database.windows.net", "demo-workwalletbi"),
				    mart_AssetInspection = Source{[Schema="mart",Item="AssetInspection"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_AssetInspection,{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"InspectedOn", "Inspected On"}, {"TotalScore", "Score"}, {"TotalPotentialScore", "Potential Score"}, {"AverageScore", "Average Score"}, {"AveragePotentialScore", "Average Potential Score"}, {"PercentageScore", "Percentage Score"}, {"ExternalIdentifier", "External Identifier"}, {"InspectedByCompany", "Inspected By Company"}, {"InProgressStatusDate", "In Progress Status Date"}, {"ReadyForReviewStatusDate", "Ready For Review Status Date"}, {"CompleteStatusDate", "Complete Status Date"}, {"ArchivedStatusDate", "Archived Status Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"In Progress Status Date", type datetime}, {"Ready For Review Status Date", type datetime}, {"Complete Status Date", type datetime}, {"Archived Status Date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

