table 'Score Tag Fact'
	lineageTag: a8a748bb-f5c4-4a00-a189-549b29f1b776

	column AssetInspection_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a709bbd0-6dd8-490e-916e-cf4752fe0cfe
		summarizeBy: none
		sourceColumn: AssetInspection_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column AssetInspectionScoreTag_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9cb0d1f6-ee13-4431-b670-551cae881b21
		summarizeBy: none
		sourceColumn: AssetInspectionScoreTag_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: int64
		formatString: 0
		lineageTag: 49f79cec-b2fe-4fb4-9c4c-d091c1fe448c
		summarizeBy: sum
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column 'Potential Score'
		dataType: int64
		formatString: 0
		lineageTag: d3805345-6dbe-49af-822c-d51bbeb820e5
		summarizeBy: sum
		sourceColumn: Potential Score

		annotation SummarizationSetBy = Automatic

	column 'Average Score'
		dataType: double
		lineageTag: 1426dbf1-2ddd-429b-9603-5b482819740b
		summarizeBy: none
		sourceColumn: Average Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Average Potential Score'
		dataType: double
		lineageTag: ee04b67a-87dc-47f4-bca6-1a04a4852df1
		summarizeBy: none
		sourceColumn: Average Potential Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Percentage Score'
		dataType: double
		lineageTag: 76eb3ab4-e025-4782-b9ec-dc16b7f64ed4
		summarizeBy: none
		sourceColumn: Percentage Score

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Defects
		dataType: int64
		formatString: 0
		lineageTag: 4b3eab94-da8f-4eea-b80b-440ac1e77380
		summarizeBy: sum
		sourceColumn: Defects

		annotation SummarizationSetBy = Automatic

	column GradingSetOption_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f9f40eec-f022-444f-9383-b5133ae67a6b
		summarizeBy: none
		sourceColumn: GradingSetOption_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 880f0685-ecf1-48bb-a4da-13db09e1d003
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Score Tag Count' = 1
		formatString: 0
		lineageTag: b8bed8af-228a-40cf-978e-565b5092853a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Score Display' =
			
			VAR DisplayScore =
			    AND(RELATED('Inspection Type'[Display Total Score]), 'Score Tag Fact'[Score] <> -1)
			VAR DisplayPercentage =
			    AND(RELATED('Inspection Type'[Display Percentage]), 'Score Tag Fact'[Percentage Score] <> -1)
			VAR ScoreText =
			    IF(DisplayScore, 'Score Tag Fact'[Score] & "/" & 'Score Tag Fact'[Potential Score], "")
			VAR PercentageText =
			    IF(DisplayPercentage, FORMAT('Score Tag Fact'[Percentage Score], "#%"), "")
			RETURN
			    IF(
			        RELATED('Inspection Type'[Scoring Enabled]),
			        IF(
			            AND(DisplayScore, DisplayPercentage),
			            ScoreText & " (" & PercentageText & ")",
			            IF(
			                DisplayScore,
			                ScoreText,
			                IF(
			                    DisplayPercentage,
			                    PercentageText,
			                    ""
			                )
			            )
			        ),
			        "scoring not enabled"
			    )
		lineageTag: 7e0a3c48-5f47-4821-bee7-53561437cadd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Score Tag Fact' = m
		mode: import
		source =
				let
				  Source = Sql.Database("demo-workwalletbi.database.windows.net", "demo-workwalletbi"),
				  #"Navigation 1" = Source{[Schema = "mart", Item = "AssetInspectionScoreTagFact"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"TotalPotentialScore", "Potential Score"}, {"TotalScore", "Score"}, {"AverageScore", "Average Score"}, {"AveragePotentialScore", "Average Potential Score"}, {"PercentageScore", "Percentage Score"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

