table 'Audit Status'
	lineageTag: fc1edad6-6431-4233-a62c-92b52a3b6880

	column SiteAuditStatus_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a4908655-2f5f-4c09-9c6a-f978455d2d67
		summarizeBy: none
		sourceColumn: SiteAuditStatus_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteAuditStatusCode
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 74e0dd08-716b-4c66-b18b-724a4f12e61b
		summarizeBy: none
		sourceColumn: SiteAuditStatusCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Audit Status'
		dataType: string
		lineageTag: 6a003ca5-59c5-4337-ab7b-0af362024ad0
		summarizeBy: none
		sourceColumn: Audit Status

		annotation SummarizationSetBy = Automatic

	partition 'Audit Status-36488214-b260-4a22-aca9-93bb63324b8b' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_SiteAuditStatus = Source{[Schema="mart",Item="SiteAuditStatus"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(mart_SiteAuditStatus,{"_created", "_edited"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"SiteAuditStatus", "Audit Status"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Exception

