table 'Checklist Fact'
	lineageTag: 2c2e64a8-ecc2-4888-b23f-d64faca7a37a

	column SiteAudit_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dbb0647b-935d-42ee-8ce6-574f6713f075
		summarizeBy: none
		sourceColumn: SiteAudit_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column SiteAuditChecklist_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 90d9267e-6fd6-4ef6-816c-e0d4c8f3dbd7
		summarizeBy: none
		sourceColumn: SiteAuditChecklist_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteAuditType_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f1ad499a-6b67-437c-94d8-69a955d91a4a
		summarizeBy: none
		sourceColumn: SiteAuditType_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Location_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 99fb753f-c256-42c2-a73b-de9eac1b6298
		summarizeBy: none
		sourceColumn: Location_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column SiteAuditStatus_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5ae9415e-b9a2-4807-ab34-4a3ac206c45a
		summarizeBy: none
		sourceColumn: SiteAuditStatus_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Wallet_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ea7b6e39-b012-429e-9830-4364fcdeba2f
		summarizeBy: none
		sourceColumn: Wallet_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Checklist Has Score'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fd4f1f5b-cd6b-49a5-bf68-a6d917e68efa
		summarizeBy: none
		sourceColumn: Checklist Has Score

		annotation SummarizationSetBy = Automatic

	column 'Checklist Score'
		dataType: double
		lineageTag: b69fd36b-135a-4c7f-b5f1-f415362637e3
		summarizeBy: sum
		sourceColumn: Checklist Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Checklist Potential Score'
		dataType: double
		lineageTag: 52ba28b5-640f-49c3-bb2b-9d4c7b0c70ea
		summarizeBy: sum
		sourceColumn: Checklist Potential Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Checklist %'
		dataType: int64
		formatString: 0
		lineageTag: 3fb14e20-134c-49d1-85aa-d590b54cdfe3
		summarizeBy: average
		sourceColumn: Checklist %

		annotation SummarizationSetBy = User

	column PassFailStatus
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4d558f9c-ebd8-43fb-a54b-55733379e3f7
		summarizeBy: none
		sourceColumn: PassFailStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Checklist Passed'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1363bdf7-b466-4083-947b-b4a54350eb02
		summarizeBy: none
		sourceColumn: Checklist Passed

		annotation SummarizationSetBy = Automatic

	column PassScore
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b9994b21-a1f2-4d6e-a1d1-57cf73b85eba
		summarizeBy: none
		sourceColumn: PassScore

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Checklist Count' = 1
		formatString: 0
		lineageTag: 9aefed9f-4e85-44ef-8d67-40985054e02e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Passed Count' = [Checklist Passed] + 0
		formatString: 0
		lineageTag: 363bf7ad-db3a-43a9-9f5f-c7e98c524844
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Checklist Fact-7c54beb5-a8cd-452d-9dfb-b734e89c1135' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ww-powerbi-demo.database.windows.net", "powerbi"),
				    mart_SiteAuditChecklistFact = Source{[Schema="mart",Item="SiteAuditChecklistFact"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(mart_SiteAuditChecklistFact,{{"HasScore", "Checklist Has Score"}, {"PotentialScore", "Checklist Potential Score"}, {"Score", "Checklist Score"}, {"Passed", "Checklist Passed"}, {"Percent", "Checklist %"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

